<?
$PERM["/"]["*"]="R";
$PERM["index.php"]["8"]="W";
$PERM["video"]["*"]="R";
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["personal"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["about"]["8"]="W";
?>